### PR TITLE
Digital book link in Catalog numbers tab

### PR DESCRIPTION
**Pull request by miri**
#190

### CODE REVIEW

**Comment by miri** [comment]
@bitamar , The PR is ready for merge.

**Comment by miri** [comment]
image

**Comment by bitamar** [comment]
@miri - Please add a behat test checking this link is shown

**Comment by miri** [comment]
The behat test added to PR  158 Add a behat tests for book tabs in the commit: "Add Catalog numbers tab with link to digital book test.".

**Comment by miri** [comment]
Merged.

**Pull request closed without merging**
